### ISSUE TITLE
fixtures used lazily are not detected

### ISSUE THREAD

**Issue by aaarrti** [jllorencetti/pytest-deadfixtures#39]
Hi, 
after I run ` pytest --dead-fixtures` I get an output e.g. 
![image](https://user-images.githubusercontent.com/44274784/189232268-e624d558-3f56-42a0-a967-075a140a30ef.png)
To double check if ii is so, I run `grep -r 'almost_uniform_1d' tests`
and get 
![image](https://user-images.githubusercontent.com/44274784/189232360-6b32ea3a-6eea-44bd-96f2-910e286ec7fe.png).
So, the fixtures are clearly used, but not detected, because of lazy loading. 
This is the plugin I use for lazy loading https://github.com/TvoroG/pytest-lazy-fixture

**Comment by jonatrios** [comment]
@aaarrti if you see source of [pytest-lazy-fixture](https://github.com/TvoroG/pytest-lazy-fixture/blob/master/pytest_lazyfixture.py#L35), you can notice that it is getting the fixture value from the method `getfixturevalue` from the built-in `request` fixture that pytest frameworks provides. So if you do this manually without using this plugin you will end up with same results. 
Few days ago I've made a patch to this behaviour to solve a similar problem that I had that is also related to the issue https://github.com/jllorencetti/pytest-deadfixtures/issues/28 but the PR is sill open: https://github.com/jllorencetti/pytest-deadfixtures/pull/38
This could be a good use case to test if the changes to support this are working as expected, or if they need to be modified again to also work with the plugin `pytest-lazy-fixture`, so please use the fork that I made and then tell me if it also helps to solve your problem. https://github.com/jonatrios/pytest-deadfixtures/tree/feature/add_support_for_parametrize_fixtures

**Comment by aaarrti** [comment]
So, I installed `pytest-dead-fixture` from source. Not this is what I get as an output:
```INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/artemsereda/anaconda3/envs/Quantus-3.9/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/artemsereda/anaconda3/envs/Quantus-3.9/lib/python3.9/site-packages/pytest_deadfixtures-3.0.0-py3.9.egg/pytest_deadfixtures.py", line 219, in show_dead_fixtures
INTERNALERROR>     param_fixtures = get_parametrized_fixtures(session, available_fixtures)
INTERNALERROR>   File "/Users/artemsereda/anaconda3/envs/Quantus-3.9/lib/python3.9/site-packages/pytest_deadfixtures-3.0.0-py3.9.egg/pytest_deadfixtures.py", line 128, in get_parametrized_fixtures
INTERNALERROR>     return [
INTERNALERROR>   File "/Users/artemsereda/anaconda3/envs/Quantus-3.9/lib/python3.9/site-packages/pytest_deadfixtures-3.0.0-py3.9.egg/pytest_deadfixtures.py", line 128, in <listcomp>
INTERNALERROR>     return [
INTERNALERROR>   File "/Users/artemsereda/anaconda3/envs/Quantus-3.9/lib/python3.9/site-packages/pytest_deadfixtures-3.0.0-py3.9.egg/pytest_deadfixtures.py", line 131, in <lambda>
INTERNALERROR>     lambda x: x.fixturedef.argname in params_values, available_fixtures
INTERNALERROR>   File "/Users/artemsereda/anaconda3/envs/Quantus-3.9/lib/python3.9/site-packages/pytest_lazyfixture.py", line 197, in __eq__
INTERNALERROR>     return self.name == other.name
INTERNALERROR> AttributeError: 'str' object has no attribute 'name'
```
Unfortunately I'm not aware of the internals neither of pytest nor of the plugin, but it looks to me like the problem is that 
because of lazy loading during the `pytest-dead-fixture` scan the fixture object is not there, but only the name of it, namely `str`.
So, should it be a feature request to `pytest-dead-fixture`? Should this be consider a bug in `pytest-lazy-fixture`? 
Or should I just close the issue, as it will not work out?

**Comment by dev-petrov** [comment]
I will add support for this in pytest-lazy-fixtures at dev-petrov/pytest-lazy-fixtures#40
